### ISSUE TITLE
Homepage Rebrand

### ISSUE THREAD

**Issue by katibest** [poanetwork/poa-explorer#108]
- [x] Navigation (#127)
- [x] POA Network Value Graph (#29)  
- [x] Footer (#139)
- [x] Social Media links (#147)
- [x] "View all" from transactions & Block Panel (#146 )
- [x] Add POA Theme (#152)

**Comment by acravenho** [comment]
Just to clarify here, a user would start a search and be sent to a loading page and then redirected to the appropriate result page?

**Comment by katibest** [comment]
User could start by searching or scroll down (which is that arrow and can say Scroll down) to the homepage. So they have options but if since a lot of people are coming in with a search in mind they can.

**Comment by acravenho** [comment]
That's an interesting concept. Most people who come to the explorer will already have the address bookmarked for their account and if they go to the homepage, they will be looking to search for an account or txid. I will have to think this over and talk with a user group to see how they would feel.

**Comment by katibest** [comment]
When you say they'll be searching for an account or Txid will they already have the number or will they be browsing through the different tables? 

From the every person persona (Bethany) I think a splash page could add a little excitement and not overwhelmed with information. We could even use it to direct them to more resources. I do note we could have the splash page to be for first time users only (using unique IDs). That way if the search bar isn't proactively used by regular users they'll automatically go to the homepage. 

I would be very interested in the what the user group thinks but I can start implementing the homepage screen, the landing page in theory should be pretty simple to implement if we decide thats the best route!

**Comment by katibest** [comment]
![img_7917](https://user-images.githubusercontent.com/20226535/38698348-b8cf6a46-3e62-11e8-8ae2-72e88815fc25.JPG)

Updated! It follows the layout we discussed  with the exception of the left sidebar. This will make navigation much much easier. If this is good with you I'll let Underdog know the wireframe has been approved so they can start design and I'll start implementing.

**Comment by katibest** [comment]
@acravenho Not sure if you saw this! Just checking in :)

**Comment by acravenho** [comment]
@katibest Looks great. Let's move forward with the design.

**Comment by katibest** [comment]
Awesome! Thank you!
