### ISSUE TITLE
Include a Token details page

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#51]
The issue includes a Token details page, where the Contributor can see information about that Token, such as its `Total Supply` and `Token Transfers`. 

The Contributor should be redirected to that page everytime she clicks on a Token link (described in the Acceptance Criteria).

![screen shot 2018-07-16 at 18 59 10](https://user-images.githubusercontent.com/2921671/42785873-6539ddc2-892a-11e8-9125-6657e6d6b0ea.png)

https://projects.invisionapp.com/share/8EMX9IOR2V9#/screens/308372327

## Acceptance criteria

- The page should have a section with:
    - the Token name
    - the Token contract Address
    - how many Addresses were involved in Token Transfers
        - Addresses that appear both in "to_address" as in "from_address"
    - how many Token Transfers have happened
    - the decimals places for that Token
- The page should have a section with the Token `Total Supply`
- The page should have a `Token Transfers` tab that lists all Token Transfers made from that Token to/from the Address.
- Each Token Transfer in the list should show:
    - The Tx hash in which the transfer has happened
    - The ID of the Block in which the transfer has happened
    - The Token Transfer From Address
    - The Token Transfer To Address
    - The number of tokens transferred
    - How much time ago has the transfer happened
- ~Token links should redirect to the Token/Address Details page~
    - ~In the Tx details page, when clicking on the Token Symbol/Name.~
    - ~In the Address Tx List, when clicking on the Token Symbol/Name.~
    - ~In the Address Token balances dropdown list, when clicking on a Token.~
- The token transfer list should be paginated.
- The token transfer list should be ordered by date, from the most recent to the older one.

### Out of scope

- The `Price` section, on the top of the page
- Conversions to USD
- Filtering the information in the page by address (#425)

## Observations

 - There's a chance of reusing this TokenTransfer tab in a [future issue](https://github.com/poanetwork/poa-explorer/issues/410)

## Dependencies

- [x] https://github.com/poanetwork/poa-explorer/pull/334

## Tasks

- [x] Create a script to populate dummy data in the database to use as test
- [x] Create Token's route (token/<address-hash>)
- [x] Create Token's view (HTML + CSS)
    - [x] Create Total Supply box
    - [x] Create the list of token transfers
    - [x] Show the contract style in the hash link when the address is a contract
- [x] Create API to get tokens info (name, address, decimal places, total supply)
    - [x] Query to count the number of addresses that were involved in token transfers
    - [x] Query to count the number or token transfers
- [x] Create API to get token transfers info
    - [x] Query to list all token transfers considering pagination

**Comment by igorffs** [comment]
@acravenho I seems that we could merge this task with #50. wdyt?

**Comment by igorffs** [comment]
> @acravenho I seems that we could merge this task with #50. wdyt?

Sorry, I got it wrong. This is actually a new page (just like this one https://etherscan.io/token/0x0e8d6b471e332f140e7d9dbb99e5e3822f728da6), it makes sense to keep it in a single issue. 👍

**Comment by acravenho** [comment]
LGTM 👍

**Comment by gfreh** [comment]
@acravenho two new questions that have just popped up: 

1. In case we have more than one Toke Transfer in the same call to the Token contract, should they be isolated in that list?
2. What links should redirect the Contributor to the Token page? At Etherscan, not all links redirect to there, and we still have the Contract Address details page.

**Comment by acravenho** [comment]
1. Since this is the token page, every token transfer should have its own box very similar to how etherscan operates.
2. Clicking a link on the address page token dropdown should bring the user to this page filtered by the user. 
Clicking on the token name from the transactions list tab should bring you to this page as well filtered by the user. There doesn't look like there is a link on mockups for this but it should be included.

**Comment by gfreh** [comment]
1. Ok!
2. Regarding this one: 
 2.1. Do you believe the filtering feature is required for the first release or can we hold it off? There is no field for that in the mockups (there is a search field but I believe that is a different thing 🤔 )
 2.2. I believe there is another place we might want to have a link to the token page: in the transaction details page, where the token symbol is shown (as described by #386). Is it correct?

**Comment by gfreh** [comment]
Hey, @amandasposito! I've been testing this issue and found some small issues I've listed below:

- [ ] There seems to be some problem with the timestamp label. For [my contract](http://localhost:4000/en/tokens/0xe49fedd93960a0267b3c3b2c1e2d66028e013fee), all transfers are labeled with the `21 hours ago` label, although they've taken place many days ago.
- [ ] Not sure if this is related to the issue above, but the sorting seems to be wrong for my contract address too.

ps.: I'll use this comment to add any issue I find.

**Comment by acravenho** [comment]
It could be an issue with the last updated timestamp instead of block validated timestamp.

**Comment by gfreh** [comment]
@acravenho Not sure if we've discussed it before, but for this page, should the transaction hash be a link to the transaction details page?

**Comment by acravenho** [comment]
Yes, the transaction has should like to the transaction details page.

**Comment by gfreh** [comment]
@acravenho All the fixes are working fine!

We have just two extra questions:

- We noticed that the burn address is being considered when calculating the number of addresses that were involved in token transfers for that token. We've noticed that Etherscan doesn't count it. Should we remove it from the count? I'm not sure what is the use case for this info, if it's required to be precise or if users just want to see the order of magnitude.
- We noticed that there is one single case in Sokol where the Token's `Total Supply` was stored as `null`. Is it something we should expect in the explorer app or should that be handled by the indexer?

**Comment by acravenho** [comment]
@gfreh 

1. When `0x0000000000000000000000000000000000000000` is the sender of tokens, they are being `minted` not transferred and when `0x0000000000000000000000000000000000000000` is the receiver of tokens they are being `burned`. We should remove these transactions from the count value as they are not true transfers.

2. We should be handling this in explorer app because it is an optional value for ERC721 and other token EIPs.

**Comment by gfreh** [comment]
As we've just discussed on a call:

1. We've misunderstood that address count in this issue. Instead of the count of addresses that have been involved in token transfers, it should display the count of addresses that have `balance > 0` for that token. Since we don't have a way to do that right now (it's being developed by #50 and #514), we'll have it fixed with the creation of the `Holders` tab.
2. In that case, for now, we're going to hide the entire `Total Supply` block. In the future, we might be able to retrieve the total supply by summing the balances of all holders.
